### ISSUE TITLE
Exception on Ubuntu when linting file from project

### ISSUE THREAD

**Issue by Bumshakalaka** [Bumshakalaka/SublimeLinter-contrib-nagelfar#4]
Error in line 106 - list index out of range
perist.print('Subfolder to rebuild: {}'.format(folder[1])

I see that:
- on windows folder list contain list e.g. ['', 'client', 'classes', 'client.tcl'] 
- on Ubuntu: /clinet/classes/client.tcl

Probably problem with split - folder = fileName.replace(masterPath,'').split('\\')

**Comment by level44** [comment]
Platform independent method for splitting paths implemented
