### ISSUE TITLE
exception when project hash generated

### ISSUE THREAD

**Issue by Bumshakalaka** [Bumshakalaka/SublimeLinter-contrib-nagelfar#5]
From the logs:

reloading settings Packages/User/SublimeLinter.sublime-settings
SublimeLinter: Rebuilding in project folder: C:\Users\...\cvs_work\ETA 
SublimeLinter: Not initial scan - rebuild only one file 
SublimeLinter: Subfolder to rebuild: ETA 
SublimeLinter: Rebuild only one database for folder C:\Users\...\cvs_work\ETA\ETA 
SublimeLinter: cache folder C:\Users\...\Tools\Sublime Text 3\Data\Cache 
SublimeLinter: project name: QzpcVXNlcnNcZHpzYzFsXGN2c193b3JrXEVUQQ== 
SublimeLinter: new cache database for folder: ETA is C:\Users\...\Tools\Sublime Text 3\Data\Cache\TCLlinter\QzpcVXNlcnNcZHpzYzFsXGN2c193b3JrXEVUQQ==\RVRB 
SublimeLinter: _rebuild called for C:\Users\...\Tools\Sublime Text 3\Data\Cache\TCLlinter\QzpcVXNlcnNcZHpzYzFsXGN2c193b3JrXEVUQQ==\RVRB\.syntaxdb 
SublimeLinter: cache folder C:\Users\...\Tools\Sublime Text 3\Data\Cache 
SublimeLinter: ERROR: Unhandled exception:

    return base64.b64encode(data.encode()).decode("utf-8").replace('/','')
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by level44** [comment]
It's always?

**Comment by level44** [comment]
@Bumshakalaka could you try to reproduce with the newest version from the database_per_folder branch?

**Comment by Bumshakalaka** [comment]
Cannot be reproduce. anyhow, there are other errors:)
