### ISSUE TITLE
Initial scan not trigged

### ISSUE THREAD

**Issue by Bumshakalaka** [Bumshakalaka/SublimeLinter-contrib-nagelfar#9]
Scenario:
1. remove cache folder
2. open rabbit_nodes project

Observed:
SublimeLinter: get_project_folder: proj_file D:\cvs_work\Samurai_2.0\Rabbit_nodes\rabbit.sublime-project 
SublimeLinter: Rebuilding in project folder: D:\cvs_work\Samurai_2.0\Rabbit_nodes 
SublimeLinter: get_project_folder: proj_file D:\cvs_work\Samurai_2.0\Rabbit_nodes\rabbit.sublime-project 
SublimeLinter: Not initial scan - rebuild only one file 
SublimeLinter: Subfolder to rebuild: node 
SublimeLinter: Rebuild only one database for folder D:\cvs_work\Samurai_2.0\Rabbit_nodes\node 
SublimeLinter: get_project_folder: proj_file D:\cvs_work\Samurai_2.0\Rabbit_nodes\rabbit.sublime-project 
SublimeLinter: cache folder D:\Program Files\Sublime Text 3\Data\Cache 
SublimeLinter: get_project_folder: proj_file D:\cvs_work\Samurai_2.0\Rabbit_nodes\rabbit.sublime-project 
SublimeLinter: project name: RDpcY3ZzX3dvcmtcU2FtdXJhaV8yLjBcUmFiYml0X25vZGVz 
....

Expected:
Initial scan shall be trigged

**Comment by level44** [comment]
Fixed
